In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

from glob import glob
from tqdm import tqdm

In [3]:
fps = glob('../slides/3_sam_masks_big_cell/*')
for fp in tqdm(fps):
    
    wing_name = fp.split('/')[-1].split('.')[0]
    mask = cv2.imread(fp, cv2.IMREAD_GRAYSCALE)
    contours, hierarchy = cv2.findContours((mask > 0).astype('uint8'), 1, 2)
    try:
        biggest_contour = contours[np.argmax([cv2.contourArea(x) for x in contours])]
        
        mask = np.zeros(mask.shape)
        cv2.drawContours(mask, [biggest_contour], 0, 1, -1)
        #plt.imshow((mask>0))
        new_fp = '../slides/4_cleaned_sam_masks_big_cell/' + wing_name + '.png'
        cv2.imwrite(new_fp, mask*255)
    except Exception as ex:
        print(ex)
        pass



  3%|████▎                                                                                                                                                               | 105/4020 [00:00<00:18, 210.61it/s]

attempt to get argmax of an empty sequence


 50%|██████████████████████████████████████████████████████████████████████████████████                                                                                 | 2025/4020 [00:06<00:06, 304.01it/s]

attempt to get argmax of an empty sequence


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4020/4020 [00:12<00:00, 323.68it/s]


In [4]:
fps = glob('../slides/3_sam_masks_medial/*')
for fp in tqdm(fps):
    
    wing_name = fp.split('/')[-1].split('.')[0]
    mask = cv2.imread(fp, cv2.IMREAD_GRAYSCALE)
    contours, hierarchy = cv2.findContours((mask > 0).astype('uint8'), 1, 2)
    try:
        biggest_contour = contours[np.argmax([cv2.contourArea(x) for x in contours])]
        
        mask = np.zeros(mask.shape)
        cv2.drawContours(mask, [biggest_contour], 0, 1, -1)
        #plt.imshow((mask>0))
        new_fp = '../slides/4_cleaned_sam_masks_medial/' + wing_name + '.png'
        cv2.imwrite(new_fp, mask*255)
    except:
        pass


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4020/4020 [00:10<00:00, 379.58it/s]


In [30]:
biggest_contour

array([[[736,  21]],

       [[735,  22]],

       [[712,  22]],

       ...,

       [[757,  22]],

       [[752,  22]],

       [[751,  21]]], dtype=int32)

In [21]:
contours

(array([[[622, 208]],
 
        [[623, 207]],
 
        [[624, 208]],
 
        [[623, 209]]], dtype=int32),
 array([[[416, 184]],
 
        [[416, 186]]], dtype=int32),
 array([[[554, 173]],
 
        [[555, 172]],
 
        [[556, 172]],
 
        [[557, 173]],
 
        [[558, 173]],
 
        [[560, 175]],
 
        [[564, 175]],
 
        [[565, 176]],
 
        [[565, 177]],
 
        [[566, 178]],
 
        [[567, 178]],
 
        [[568, 179]],
 
        [[568, 180]],
 
        [[569, 180]],
 
        [[570, 181]],
 
        [[572, 181]],
 
        [[573, 182]],
 
        [[573, 183]],
 
        [[574, 184]],
 
        [[575, 184]],
 
        [[576, 185]],
 
        [[577, 185]],
 
        [[579, 187]],
 
        [[580, 187]],
 
        [[582, 189]],
 
        [[583, 189]],
 
        [[584, 190]],
 
        [[584, 191]],
 
        [[586, 191]],
 
        [[587, 192]],
 
        [[588, 192]],
 
        [[591, 195]],
 
        [[591, 196]],
 
        [[593, 196]],
 
        [[594,